---
apiVersion: app/v1
kind: Deployment
Metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    author: nene
spec:
  replicas: 2
  selector:
    matchLabels:
    name: postgres-deployment
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: nene
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: myuser
...