---
apiVersion: app/v1
kind: Deployment
Metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    author: nene
spec:
  replicas: 2
  selector:
    matchLabels:
    name: redis-deployment
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-deployment
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
...